title: Arjun Thakur | Programmer, Web Developer, UI/UX Designer
name: Arjun Thakur
email: arjunthakur01081997@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio of Arjun Thakur - A programmer, web developer and a UI/UX designer from Himachal Pradesh, India. Passionate about Creating Graphics & Animations. Networking Enthusiast. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arjunthakur08.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: arjunthakur08
github_username: arjunthakur08

permalink: slug

exclude:
   - .jekyll-cache/
   - .sass-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - readme.md
   - license
   - CNAME
   
plugins:
  - jekyll-sitemap

strict_front_matter: true
sass:
  style: compressed # possible values: nested expanded compact compressed
  
# Compressing HTML  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
